In [2]:
from google.colab import files
uploaded = files.upload()

Saving annual_conc_by_monitor_2025.csv to annual_conc_by_monitor_2025.csv

In [3]:
import pandas as pd
import numpy as np

# Load datasets
conc = pd.read_csv('annual_conc_by_monitor_2025.csv')
sites = pd.read_csv('aqs_sites.csv')

# Preview
print(conc.shape)
print(sites.shape)

conc.head()

(59154, 55)
(20952, 28)

,State Code,County Code,Site Num,Parameter Code,POC,Latitude,Longitude,Datum,Parameter Name,Sample Duration,...,75th Percentile,50th Percentile,10th Percentile,Local Site Name,Address,State Name,County Name,City Name,CBSA Name,Date of Last Change
0,1,3,10,44201,1,30.497478,-87.880258,NAD83,Ozone,1 HOUR,...,0.054,0.045,0.029,"FAIRHOPE, Alabama","FAIRHOPE HIGH SCHOOL, 1 PIRATE DRIVE, FAIRHOPE...",Alabama,Baldwin,Fairhope,"Daphne-Fairhope-Foley, AL",2025-10-29
1,1,3,10,44201,1,30.497478,-87.880258,NAD83,Ozone,8-HR RUN AVG BEGIN HOUR,...,0.049,0.040,0.026,"FAIRHOPE, Alabama","FAIRHOPE HIGH SCHOOL, 1 PIRATE DRIVE, FAIRHOPE...",Alabama,Baldwin,Fairhope,"Daphne-Fairhope-Foley, AL",2025-10-29
2,1,3,10,44201,1,30.497478,-87.880258,NAD83,Ozone,8-HR RUN AVG BEGIN HOUR,...,0.049,0.040,0.026,"FAIRHOPE, Alabama","FAIRHOPE HIGH SCHOOL, 1 PIRATE DRIVE, FAIRHOPE...",Alabama,Baldwin,Fairhope,"Daphne-Fairhope-Foley, AL",2025-10-29
3,1,3,10,44201,1,30.497478,-87.880258,NAD83,Ozone,8-HR RUN AVG BEGIN HOUR,...,0.049,0.040,0.026,"FAIRHOPE, Alabama","FAIRHOPE HIGH SCHOOL, 1 PIRATE DRIVE, FAIRHOPE...",Alabama,Baldwin,Fairhope,"Daphne-Fairhope-Foley, AL",2025-10-29
4,1,3,10,88101,3,30.497478,-87.880258,NAD83,PM2.5 - Local Conditions,1 HOUR,...,10.000,6.000,1.000,"FAIRHOPE, Alabama","FAIRHOPE HIGH SCHOOL, 1 PIRATE DRIVE, FAIRHOPE...",Alabama,Baldwin,Fairhope,"Daphne-Fairhope-Foley, AL",2025-10-29

In [4]:
#data profiling
# Basic info
conc.info()
sites.info()

# Missing values
conc.isnull().sum().sort_values(ascending=False).head(20)
sites.isnull().sum().sort_values(ascending=False).head(20)

# Summary stats
conc.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59154 entries, 0 to 59153
Data columns (total 55 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   State Code                     59154 non-null  int64
 1   County Code                    59154 non-null  int64
 2   Site Num                       59154 non-null  int64
 3   Parameter Code                 59154 non-null  int64
 4   POC                            59154 non-null  int64
 5   Latitude                       59154 non-null  float64
 6   Longitude                      59154 non-null  float64
 7   Datum                          59154 non-null  object
 8   Parameter Name                 59154 non-null  object
 9   Sample Duration                59154 non-null  object
 10  Pollutant Standard             21103 non-null  object
 11  Metric Used                    59154 non-null  object
 12  Method Name                    45856 non-null  object
 13  Year                           59154 non-null  int64
 14  Units of Measure               59154 non-null  object
 15  Event Type                     59154 non-null  object
 16  Observation Count              59154 non-null  int64
 17  Observation Percent            59154 non-null  int64
 18  Completeness Indicator         59154 non-null  object
 19  Valid Day Count                59154 non-null  int64
 20  Required Day Count             59154 non-null  int64
 21  Exceptional Data Count         59154 non-null  int64
 22  Null Data Count                59154 non-null  int64
 23  Primary Exceedance Count       13412 non-null  float64
 24  Secondary Exceedance Count     12606 non-null  float64
 25  Certification Indicator        59154 non-null  object
 26  Num Obs Below MDL              59154 non-null  int64
 27  Arithmetic Mean                59154 non-null  float64
 28  Arithmetic Standard Dev        59154 non-null  float64
 29  1st Max Value                  59154 non-null  float64
 30  1st Max DateTime               59154 non-null  object
 31  2nd Max Value                  59046 non-null  float64
 32  2nd Max DateTime               59046 non-null  object
 33  3rd Max Value                  58906 non-null  float64
 34  3rd Max DateTime               58906 non-null  object
 35  4th Max Value                  58773 non-null  float64
 36  4th Max DateTime               58773 non-null  object
 37  1st Max Non Overlapping Value  213 non-null    float64
 38  1st NO Max DateTime            213 non-null    object
 39  2nd Max Non Overlapping Value  213 non-null    float64
 40  2nd NO Max DateTime            213 non-null    object
 41  99th Percentile                59154 non-null  float64
 42  98th Percentile                59154 non-null  float64
 43  95th Percentile                59154 non-null  float64
 44  90th Percentile                59137 non-null  float64
 45  75th Percentile                59137 non-null  float64
 46  50th Percentile                59137 non-null  float64
 47  10th Percentile                59126 non-null  float64
 48  Local Site Name                57571 non-null  object
 49  Address                        59153 non-null  object
 50  State Name                     59154 non-null  object
 51  County Name                    59154 non-null  object
 52  City Name                      46599 non-null  object
 53  CBSA Name                      53177 non-null  object
 54  Date of Last Change            59154 non-null  object
dtypes: float64(19), int64(13), object(23)
memory usage: 24.8+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20952 entries, 0 to 20951
Data columns (total 28 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   State Code             20952 non-null  object
 1   County Code            20952 non-null  int64
 2   Site Number            20952 non-null  int64
 3   Latitude               20945 non-null  float64
 4   Longitude              20946 non-null  float64
 5   Datum                  20952 non-null  object
 6   Elevation              20952 non-null  float64
 7   Land Use               19803 non-null  object
 8   Location Setting       19935 non-null  object
 9   Site Established Date  20952 non-null  object
 10  Site Closed Date       16220 non-null  object
 11  Met Site State Code    437 non-null    float64
 12  Met Site County Code   437 non-null    float64
 13  Met Site Site Number   437 non-null    float64
 14  Met Site Type          2139 non-null   object
 15  Met Site Distance      643 non-null    float64
 16  Met Site Direction     598 non-null    object
 17  GMT Offset             20952 non-null  int64
 18  Owning Agency          20952 non-null  object
 19  Local Site Name        6381 non-null   object
 20  Address                20948 non-null  object
 21  Zip Code               10894 non-null  float64
 22  State Name             20952 non-null  object
 23  County Name            20952 non-null  object
 24  City Name              20952 non-null  object
 25  CBSA Name              18327 non-null  object
 26  Tribe Name             257 non-null    object
 27  Extraction Date        20952 non-null  object
dtypes: float64(8), int64(3), object(17)
memory usage: 4.5+ MB

,State Code,County Code,Site Num,Parameter Code,POC,Latitude,Longitude,Year,Observation Count,Observation Percent,...,4th Max Value,1st Max Non Overlapping Value,2nd Max Non Overlapping Value,99th Percentile,98th Percentile,95th Percentile,90th Percentile,75th Percentile,50th Percentile,10th Percentile
count,59154.000000,59154.000000,59154.000000,59154.000000,59154.000000,59154.000000,59154.000000,59154.0,59154.000000,59154.000000,...,58773.000000,213.000000,213.000000,59154.000000,59154.000000,59154.000000,59137.000000,59137.000000,59137.000000,59126.000000
mean,28.008993,74.995655,1233.484261,69926.147040,3.305541,38.611204,-95.847159,2025.0,1587.186327,47.271782,...,65.160914,1.053991,0.917840,54.074385,49.823232,44.050799,39.905691,34.350019,29.781987,23.476319
std,16.806153,88.011693,2541.393274,21386.210499,6.896718,5.824937,17.782925,0.0,4038.240187,21.849763,...,1461.852374,0.799319,0.627935,988.591111,847.183302,655.456250,515.072929,337.196244,226.848427,149.542925
min,1.000000,1.000000,1.000000,11101.000000,1.000000,17.955378,-160.508331,2025.0,1.000000,0.000000,...,-30.000000,0.000000,0.000000,-30.000000,-31.000000,-33.000000,-34.000000,-40.000000,-44.000000,-46.000000
25%,12.000000,21.000000,8.000000,44201.000000,1.000000,34.785219,-111.657936,2025.0,25.000000,34.000000,...,0.065000,0.600000,0.600000,0.073775,0.070000,0.064000,0.058000,0.049000,0.036000,0.001000
50%,28.000000,51.000000,32.000000,88101.000000,2.000000,39.464872,-91.179219,2025.0,60.000000,47.000000,...,1.783820,0.900000,0.800000,2.200000,2.000000,1.500000,1.173980,0.800000,0.478000,0.160000
75%,42.000000,99.000000,1011.000000,88112.000000,5.000000,41.753873,-81.678449,2025.0,2835.750000,66.000000,...,21.100000,1.200000,1.100000,23.200000,20.200000,15.900000,12.900000,9.300000,6.400000,3.100000
max,80.000000,810.000000,9997.000000,88503.000000,82.000000,68.637233,-64.795972,2025.0,86042.000000,100.000000,...,201581.000000,6.900000,5.400000,135129.000000,115311.000000,85921.000000,62176.000000,34111.000000,19643.000000,8085.000000

In [5]:
#completeness check
# % missing values
missing_conc = conc.isnull().mean() * 100
missing_sites = sites.isnull().mean() * 100

missing_conc.sort_values(ascending=False).head(10)
missing_sites.sort_values(ascending=False).head(10)

Tribe Name              98.773387
Met Site State Code     97.914280
Met Site County Code    97.914280
Met Site Site Number    97.914280
Met Site Direction      97.145857
Met Site Distance       96.931081
Met Site Type           89.790951
Local Site Name         69.544674
Zip Code                48.004964
Site Closed Date        22.584956
dtype: float64

In [6]:
#checking duplicates
# Check duplicates
conc_duplicates = conc.duplicated().sum()
sites_duplicates = sites.duplicated().sum()

print("Conc duplicates:", conc_duplicates)
print("Sites duplicates:", sites_duplicates)

Conc duplicates: 0
Sites duplicates: 0

In [7]:
#validity check
# Check extreme values (example column)
conc['Arithmetic Mean'].describe()

# Find suspicious values
conc[conc['Arithmetic Mean'] < 0]
conc[conc['Arithmetic Mean'] > 500]  # threshold depends on pollutant

,State Code,County Code,Site Num,Parameter Code,POC,Latitude,Longitude,Datum,Parameter Name,Sample Duration,...,75th Percentile,50th Percentile,10th Percentile,Local Site Name,Address,State Name,County Name,City Name,CBSA Name,Date of Last Change
77,1,73,23,68108,1,33.553056,-86.815000,WGS84,Average Ambient Pressure,24 HOUR,...,748.0,746.0,741.0,North Birmingham,"NO. B'HAM,SOU R.R., 3009 28TH ST. NO.",Alabama,Jefferson,Birmingham,"Birmingham-Hoover, AL",2025-10-14
78,1,73,23,68108,5,33.553056,-86.815000,WGS84,Average Ambient Pressure,24 HOUR,...,750.0,747.0,743.0,North Birmingham,"NO. B'HAM,SOU R.R., 3009 28TH ST. NO.",Alabama,Jefferson,Birmingham,"Birmingham-Hoover, AL",2025-11-04
86,1,73,23,68118,5,33.553056,-86.815000,WGS84,Average Ambient Pressure for URG3000N,24 HOUR,...,751.0,749.0,745.0,North Birmingham,"NO. B'HAM,SOU R.R., 3009 28TH ST. NO.",Alabama,Jefferson,Birmingham,"Birmingham-Hoover, AL",2025-11-04
225,1,73,1005,68108,1,33.331111,-87.003611,WGS84,Average Ambient Pressure,24 HOUR,...,751.0,749.0,744.0,McAdory,ROUTE 8 MCADORY,Alabama,Jefferson,NaN,"Birmingham-Hoover, AL",2025-10-14
250,1,73,1010,68108,1,33.545278,-86.549167,WGS84,Average Ambient Pressure,24 HOUR,...,748.0,747.0,742.0,Leeds,201 ASHVILLE ROAD,Alabama,Jefferson,Leeds,"Birmingham-Hoover, AL",2025-10-14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58962,72,21,10,68108,1,18.420089,-66.150615,WGS84,Average Ambient Pressure,24 HOUR,...,763.0,762.0,760.0,Bayamon,Ave. Central Correccional,Puerto Rico,Bayamon,Bayamon,"San Juan-Carolina-Caguas, PR",2025-10-09
59003,72,25,7,68108,1,18.198712,-66.052237,NAD83,Average Ambient Pressure,24 HOUR,...,757.0,754.0,752.0,NaN,Luis A. Ferre Highway,Puerto Rico,Caguas,Caguas,"San Juan-Carolina-Caguas, PR",2025-10-09
59031,72,53,3,68108,1,18.383983,-65.618888,WGS84,Average Ambient Pressure,24 HOUR,...,760.0,759.0,757.0,Fajardo,"FAJARDO LIGHTHOUSE,FAJARDO",Puerto Rico,Fajardo,NaN,"San Juan-Carolina-Caguas, PR",2025-10-09
59044,72,61,5,68108,1,18.440095,-66.114460,WGS84,Average Ambient Pressure,24 HOUR,...,763.0,763.0,760.0,Guaynabo,ELECTRICAL SUBSTATION NEAR PUMPHOUSE,Puerto Rico,Guaynabo,Guaynabo,"San Juan-Carolina-Caguas, PR",2025-10-09
59073,72,113,4,68108,1,18.009558,-66.627249,WGS84,Average Ambient Pressure,24 HOUR,...,763.0,762.0,760.0,RESIDENTIAL AREA,CIVIL DEFENSEBLDG. SAN ANTONIO URB. PONC,Puerto Rico,Ponce,Ponce,"Ponce, PR",2025-10-20

In [18]:
print(conc[['State Code', 'County Code', 'Site Num']].dtypes)
print(sites[['State Code', 'County Code', 'Site Num']].dtypes)

State Code     object
County Code    object
Site Num       object
dtype: object
State Code     object
County Code    object
Site Num       object
dtype: object

In [17]:
# Convert keys to string in BOTH datasets
for col in ['State Code', 'County Code', 'Site Num']:
    conc[col] = conc[col].astype(str)
    sites[col] = sites[col].astype(str)

In [14]:
print(conc.columns.tolist())
print(sites.columns.tolist())

['State Code', 'County Code', 'Site Num', 'Parameter Code', 'POC', 'Latitude', 'Longitude', 'Datum', 'Parameter Name', 'Sample Duration', 'Pollutant Standard', 'Metric Used', 'Method Name', 'Year', 'Units of Measure', 'Event Type', 'Observation Count', 'Observation Percent', 'Completeness Indicator', 'Valid Day Count', 'Required Day Count', 'Exceptional Data Count', 'Null Data Count', 'Primary Exceedance Count', 'Secondary Exceedance Count', 'Certification Indicator', 'Num Obs Below MDL', 'Arithmetic Mean', 'Arithmetic Standard Dev', '1st Max Value', '1st Max DateTime', '2nd Max Value', '2nd Max DateTime', '3rd Max Value', '3rd Max DateTime', '4th Max Value', '4th Max DateTime', '1st Max Non Overlapping Value', '1st NO Max DateTime', '2nd Max Non Overlapping Value', '2nd NO Max DateTime', '99th Percentile', '98th Percentile', '95th Percentile', '90th Percentile', '75th Percentile', '50th Percentile', '10th Percentile', 'Local Site Name', 'Address', 'State Name', 'County Name', 'City Name', 'CBSA Name', 'Date of Last Change']
['State Code', 'County Code', 'Site Num', 'Latitude', 'Longitude', 'Datum', 'Elevation', 'Land Use', 'Location Setting', 'Site Established Date', 'Site Closed Date', 'Met Site State Code', 'Met Site County Code', 'Met Site Site Number', 'Met Site Type', 'Met Site Distance', 'Met Site Direction', 'GMT Offset', 'Owning Agency', 'Local Site Name', 'Address', 'Zip Code', 'State Name', 'County Name', 'City Name', 'CBSA Name', 'Tribe Name', 'Extraction Date']

In [13]:
# Rename in sites dataset
sites = sites.rename(columns={'Site Number': 'Site Num'})

In [20]:
#consistency check
# Create join keys
keys = ['State Code', 'County Code', 'Site Num']

merged = pd.merge(conc, sites, on=keys, how='left', indicator=True)

merged['_merge'].value_counts()

_merge
both          46169
left_only     12985
right_only        0
Name: count, dtype: int64

In [21]:
merged['_merge'].value_counts(normalize=True)

_merge
both          0.780488
left_only     0.219512
right_only    0.000000
Name: proportion, dtype: float64

In [22]:
unmatched = merged[merged['_merge'] == 'left_only']

unmatched[['State Code', 'County Code', 'Site Num']].head()

  State Code County Code Site Num
0          1           3       10
1          1           3       10
2          1           3       10
3          1           3       10
4          1           3       10

In [23]:
# Which states have most missing metadata?
unmatched['State Code'].value_counts().head(10)

State Code
6    6482
8    2164
4    1956
1     742
2     733
5     470
9     438
Name: count, dtype: int64

In [26]:
conc.duplicated().sum()
conc['Arithmetic Mean'].describe()

count    59154.000000
mean        30.966771
std        274.983466
min        -42.254777
25%          0.042462
50%          0.615807
75%          7.497826
max      27312.765742
Name: Arithmetic Mean, dtype: float64